### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by PabloPG** [parsedown/laravel#2]
How i can install this in Lumen?

**Comment by eagostini** [comment]
Hey @PabloPG! It's something to be worked around as I struggled to enable **Blade** as a facade over **Lumen 5.4** (believe me, I've tried many things). It might be related to laravel/lumen-framework#504. Anyway, I found a way to do it:

### Enable Facades in Your Lumen Project

In your `bootstrap/app.php` ensure you have the following:

```php
$app->withFacades();
```

### Service Provider Registering

As **Lumen** does not support [package auto-discovery](https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518) you got to do it manually in your `bootstrap/app.php`:

```php
$app->register(Parsedown\Providers\ParsedownServiceProvider::class);
```

### Considerations

Be sure you're not displaying views under caching running `php artisan cache:clear`. I will update the service provider to load the facade directly from `Illuminate\Support\Facades\Blade` instead of `\Blade` as Lumen apparently is not handling it properly (check referred issue). That should be enough. I will keep you up to date as would be good to have some instructions for **Lumen** in our `README.md` as well.

**Comment by eagostini** [comment]
It's now implemented and will come up in the next release, today yet.

**Comment by PabloPG** [comment]
@eagostini  Sorry it took me so long to reply.

Thanks.

**Comment by marlonob** [comment]
Hello! I followed the steps here, but I get an error when I try to use it in a blade view (like in `@parsedown('hello')`). It gets me “Call to undefined function resolve()” and points to the view without a line number.

I’m using Lumen 5.5.2 and parsedown/laravel 1.0

**Comment by eagostini** [comment]
Hi @zorrillodepeluche, I will take a look at this to try to reproduce your scenario. I am currently off for some days. As soon as I can I will come back to you.

**Comment by eagostini** [comment]
The helper `resolve` is not present in **Lumen** anymore. That's why the issue came up. I will be releasing a fix for that very soon.

**Comment by eagostini** [comment]
Hi @zorrillodepeluche, I've just released a fix for your issue. Thanks for reporting!

**Comment by marlonob** [comment]
Can confirm that version 1.1 is working in Lumen as expected. Thank you.
